### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by beauvais** [beauvais/twitter_nltk#2]
When running _tokens_no_function.py_, Python throws the UnicodeDecodeError exception:

$twitter_nltk zach$ python tokens_no_function.py 
Traceback (most recent call last):
  File "tokens_no_function.py", line 9, in <module>
    tokens = word_tokenize(raw.decode('utf-8'))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0x89 in position 66: invalid start byte

**Comment by beauvais** [comment]
Weird thing is, when I run this with my full archive, not the dummy one I've created (edited down for this public repo), I don't get this exception. I'm running identical scripts over data which only differs in length, and getting completely different outcomes.

**Comment by beauvais** [comment]
[last commit](https://github.com/beauvais/twitter_nltk/commit/378eab3a03db96f3871a3fb33cdbdd74f80b33fd) used enforced utf-8 encoding on the csv file. Then I reran _import.py_, and got it to work.
